# Domain verification and basic asset info
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"
# Organization Documentation
[[PRINCIPALS]]
name="CHAU TECHNOLOGIES SL"
email="deseos@chau.es"
url="https://www.chau.es"
# Asset information
[[CURRENCIES]]
code="WILL"
issuer="GDYED56LQOLZWMYVOP5KRLSKKR6BEKYTJNUEMJJBKQOJOH25DGN5EXTY"
status="live"
display_decimals=0
name="WILL Token"
desc="WILL token represents a Proof of Testament, serving as an immutable blockchain record of wills written through CHAU's services. Each token, combined with its transaction memo, provides additional security and verification for holographic testament records."
conditions="Not intended for trading. Each token represents a unique testament record."
image="https://cdn.prod.website-files.com/66532ab2aa5ad338906ddfe2/67bdc2400b7a191151aa6d0f_Will%20-%20Chau.png"
is_asset_anchored=false
anchor_asset_type="other"
is_unlimited=true
is_asset_transferable=true
documentation="https://www.chau.es/testamentos-y-blockchain"
